In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
! wget https://raw.githubusercontent.com/dataprofessor/AMP/main/train_po.fasta

--2026-06-06 16:19:55--  https://raw.githubusercontent.com/dataprofessor/AMP/main/train_po.fasta
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52619 (51K) [text/plain]
Saving to: ‘train_po.fasta.1’

train_po.fasta.1    100%[===================>]  51.39K  --.-KB/s    in 0.007s

2026-06-06 16:19:55 (7.54 MB/s) - ‘train_po.fasta.1’ saved [52619/52619]

In [37]:
! wget https://raw.githubusercontent.com/dataprofessor/AMP/main/train_ne.fasta

--2026-06-06 16:19:55--  https://raw.githubusercontent.com/dataprofessor/AMP/main/train_ne.fasta
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57206 (56K) [text/plain]
Saving to: ‘train_ne.fasta.1’

train_ne.fasta.1    100%[===================>]  55.87K  --.-KB/s    in 0.006s

2026-06-06 16:19:56 (9.62 MB/s) - ‘train_ne.fasta.1’ saved [57206/57206]

In [38]:
! pip install biopython

Requirement already satisfied: biopython in /usr/local/lib/python3.12/dist-packages (1.87)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)

In [39]:
!pip install pfeature

Requirement already satisfied: pfeature in /usr/local/lib/python3.12/dist-packages (1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pfeature) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pfeature) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pfeature) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pfeature) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pfeature) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pfeature) (1.17.0)

In [40]:
!apt-get update
!apt-get install -y cd-hit

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.3 MB]
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,043 kB]
Fetched 13.4 MB in 2s (5,677 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cd-hit is already the newest version (4.8.1-4).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

Repeating sequences removed using CD-HIT

In [41]:
! cd-hit -i train_po.fasta -o train_po_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1 (+OpenMP), Aug 20 2021, 08:39:56
Command: cd-hit -i train_po.fasta -o train_po_cdhit.txt -c
         0.99

Started: Sat Jun  6 16:20:20 2026
================================================================
                            Output
----------------------------------------------------------------
total seq: 1445
longest and shortest : 30 and 11
Total letters: 30071
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 76M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90485873

comparing sequences from          0  to       1445
.
     1445  finished       1337  clusters

Approximated maximum memory consumption: 76M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [42]:
! cd-hit -i train_ne.fasta -o train_ne_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1 (+OpenMP), Aug 20 2021, 08:39:56
Command: cd-hit -i train_ne.fasta -o train_ne_cdhit.txt -c
         0.99

Started: Sat Jun  6 16:20:20 2026
================================================================
                            Output
----------------------------------------------------------------
total seq: 1445
longest and shortest : 30 and 11
Total letters: 30071
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 76M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90485331

comparing sequences from          0  to       1445
.
     1445  finished       1422  clusters

Approximated maximum memory consumption: 76M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [43]:
!ls -l

total 10604
-rw-r--r-- 1 root root  122465 Jun  6 13:56 aac.csv
-rw-r--r-- 1 root root  130978 Jun  6 13:57 aacneg.csv
-rw-r--r-- 1 root root 2163384 Jun  6 13:57 dpc.csv
-rw-r--r-- 1 root root 2301040 Jun  6 13:58 dpcneg.csv
-rw-r--r-- 1 root root 5203380 Jun  6 15:11 features.csv
-rw-r--r-- 1 root root  229234 Jun  6 13:57 pcp.csv
-rw-r--r-- 1 root root  245861 Jun  6 13:58 pcpneg.csv
drwxr-xr-x 1 root root    4096 Jun  4 13:32 sample_data
-rw-r--r-- 1 root root   54341 Jun  6 16:20 train_ne_cdhit.txt
-rw-r--r-- 1 root root   61425 Jun  6 16:20 train_ne_cdhit.txt.clstr
-rw-r--r-- 1 root root   57206 Jun  6 13:56 train_ne.fasta
-rw-r--r-- 1 root root   57206 Jun  6 16:19 train_ne.fasta.1
-rw-r--r-- 1 root root   47229 Jun  6 16:20 train_po_cdhit.txt
-rw-r--r-- 1 root root   56665 Jun  6 16:20 train_po_cdhit.txt.clstr
-rw-r--r-- 1 root root   52619 Jun  6 13:56 train_po.fasta
-rw-r--r-- 1 root root   52619 Jun  6 16:19 train_po.fasta.1

In [44]:
! grep ">" train_po_cdhit.txt | wc -l

1337

In [45]:
! grep ">" train_po.fasta | wc -l

1529

Calculating features for positive class

In [46]:
!pfeature_comp -i train_po_cdhit.txt -j AAC -o aac.csv

Summary of Parameters:

Input File: train_po_cdhit.txt ; Job: AAC ; Output File: aac.csv

In [47]:
!pfeature_comp -i train_po_cdhit.txt -j DPC -o dpc.csv

Summary of Parameters:

Input File: train_po_cdhit.txt ; Job: DPC ; Output File: dpc.csv

In [48]:
!pfeature_comp -i train_po_cdhit.txt -j PCP -o pcp.csv

Summary of Parameters:

Input File: train_po_cdhit.txt ; Job: PCP ; Output File: pcp.csv

In [49]:
aac = pd.read_csv('aac.csv')
dpc = pd.read_csv('dpc.csv')
pcp = pd.read_csv('pcp.csv')

featpos = pd.concat([aac, dpc, pcp], axis = 1)

In [50]:
featpos.head()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PCP_SA_EX,PCP_SA_IN,PCP_TN,PCP_SM,PCP_LR,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5
0,27.27,0.00,9.09,0.00,9.09,9.09,0.00,0.0,0.0,0.00,...,0.273,0.182,0.364,0.818,0.182,-0.345,-0.827,0.489,-0.479,0.230
1,0.00,54.55,0.00,9.09,0.00,0.00,0.00,0.0,0.0,0.00,...,0.091,0.364,0.727,0.909,0.091,1.312,-1.478,2.019,-0.696,-1.419
2,0.00,0.00,9.09,18.18,9.09,9.09,9.09,0.0,0.0,9.09,...,0.455,0.364,0.091,0.455,0.545,-0.231,-0.213,0.410,-0.286,0.289
3,0.00,0.00,0.00,18.18,9.09,9.09,9.09,0.0,0.0,9.09,...,0.455,0.364,0.091,0.455,0.545,-0.315,-0.150,0.329,-0.167,0.075
4,0.00,0.00,9.09,18.18,18.18,9.09,0.00,0.0,0.0,9.09,...,0.545,0.273,0.091,0.455,0.545,-0.326,0.174,0.717,-0.619,0.080

In [93]:
featpos.shape

(1337, 451)

In [51]:
len(featpos)

1337

In [52]:
#adding labels
featpos['label'] = 'AMP'

In [53]:
featpos.head()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PCP_SA_IN,PCP_TN,PCP_SM,PCP_LR,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5,label
0,27.27,0.00,9.09,0.00,9.09,9.09,0.00,0.0,0.0,0.00,...,0.182,0.364,0.818,0.182,-0.345,-0.827,0.489,-0.479,0.230,AMP
1,0.00,54.55,0.00,9.09,0.00,0.00,0.00,0.0,0.0,0.00,...,0.364,0.727,0.909,0.091,1.312,-1.478,2.019,-0.696,-1.419,AMP
2,0.00,0.00,9.09,18.18,9.09,9.09,9.09,0.0,0.0,9.09,...,0.364,0.091,0.455,0.545,-0.231,-0.213,0.410,-0.286,0.289,AMP
3,0.00,0.00,0.00,18.18,9.09,9.09,9.09,0.0,0.0,9.09,...,0.364,0.091,0.455,0.545,-0.315,-0.150,0.329,-0.167,0.075,AMP
4,0.00,0.00,9.09,18.18,18.18,9.09,0.00,0.0,0.0,9.09,...,0.273,0.091,0.455,0.545,-0.326,0.174,0.717,-0.619,0.080,AMP

Calculating features for negative class

In [54]:
!pfeature_comp -i train_ne_cdhit.txt -j AAC -o aacneg.csv

Summary of Parameters:

Input File: train_ne_cdhit.txt ; Job: AAC ; Output File: aacneg.csv

In [55]:
!pfeature_comp -i train_ne_cdhit.txt -j DPC -o dpcneg.csv

Summary of Parameters:

Input File: train_ne_cdhit.txt ; Job: DPC ; Output File: dpcneg.csv

In [56]:
!pfeature_comp -i train_ne_cdhit.txt -j PCP -o pcpneg.csv

Summary of Parameters:

Input File: train_ne_cdhit.txt ; Job: PCP ; Output File: pcpneg.csv

In [57]:
aacneg = pd.read_csv('aacneg.csv')
dpcneg = pd.read_csv('dpcneg.csv')
pcpneg = pd.read_csv('pcpneg.csv')

featneg = pd.concat([aacneg, dpcneg, pcpneg], axis = 1)

In [58]:
featneg['label'] = 'non-AMP'

In [59]:
featneg.head()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PCP_SA_IN,PCP_TN,PCP_SM,PCP_LR,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5,label
0,0.00,0.0,0.00,0.00,0.00,27.27,0.0,0.00,0.00,9.09,...,0.273,0.455,0.636,0.364,1.055,-0.836,-0.471,-0.358,-0.218,non-AMP
1,0.00,0.0,0.00,0.00,9.09,27.27,0.0,9.09,0.00,9.09,...,0.364,0.364,0.636,0.364,-0.045,-1.448,-0.346,-0.464,0.095,non-AMP
2,9.09,0.0,9.09,9.09,9.09,9.09,0.0,9.09,0.00,0.00,...,0.364,0.273,0.636,0.364,0.200,-0.249,0.482,-0.369,0.687,non-AMP
3,9.09,0.0,0.00,0.00,9.09,18.18,0.0,9.09,0.00,18.18,...,0.273,0.364,0.545,0.455,-0.885,-0.987,-0.089,-0.138,0.578,non-AMP
4,9.09,0.0,9.09,0.00,18.18,0.00,0.0,0.00,9.09,0.00,...,0.273,0.182,0.545,0.455,0.725,0.514,0.113,-0.114,-0.271,non-AMP

In [92]:
featneg.shape

(1422, 451)

In [60]:
features = pd.concat([featpos, featneg], axis = 0)

In [61]:
features.shape

(2759, 451)

In [62]:
features.to_csv('features.csv', index = False)

Assigning X and Y

In [65]:
x = features.drop('label', axis = 1)
y = features['label'].copy()

In [66]:
y = y.map({'AMP' : 1, 'non-AMP': 0})

In [68]:
y

0       1
1       1
2       1
3       1
4       1
       ..
1417    0
1418    0
1419    0
1420    0
1421    0
Name: label, Length: 2759, dtype: int64

Feature Selection

In [69]:
from sklearn.feature_selection import VarianceThreshold

fs = VarianceThreshold(threshold = 0.1)
fs.fit_transform(x)

x2 = x.loc[:, fs.get_support()]
x2

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YY,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5
0,27.27,0.00,9.09,0.00,9.09,9.09,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,-0.345,-0.827,0.489,-0.479,0.230
1,0.00,54.55,0.00,9.09,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,1.312,-1.478,2.019,-0.696,-1.419
2,0.00,0.00,9.09,18.18,9.09,9.09,9.09,0.00,0.00,9.09,...,0.0,0.0,0.0,0.0,0.0,-0.231,-0.213,0.410,-0.286,0.289
3,0.00,0.00,0.00,18.18,9.09,9.09,9.09,0.00,0.00,9.09,...,0.0,0.0,0.0,0.0,0.0,-0.315,-0.150,0.329,-0.167,0.075
4,0.00,0.00,9.09,18.18,18.18,9.09,0.00,0.00,0.00,9.09,...,0.0,0.0,0.0,0.0,0.0,-0.326,0.174,0.717,-0.619,0.080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,13.33,0.00,3.33,3.33,0.00,13.33,0.00,3.33,26.67,10.00,...,0.0,0.0,0.0,0.0,0.0,0.193,-0.368,-0.596,0.286,0.145
1418,6.67,0.00,0.00,3.33,6.67,20.00,3.33,3.33,13.33,13.33,...,0.0,0.0,0.0,0.0,0.0,0.058,-1.056,-0.479,-0.250,0.257
1419,6.67,20.00,0.00,3.33,0.00,10.00,0.00,6.67,10.00,3.33,...,0.0,0.0,0.0,0.0,0.0,0.092,-1.202,0.436,-0.352,-0.416
1420,6.67,0.00,3.33,3.33,6.67,0.00,3.33,3.33,3.33,6.67,...,0.0,0.0,0.0,0.0,0.0,0.271,0.178,-0.369,-0.252,-0.074
1421,0.00,20.00,6.67,6.67,0.00,6.67,6.67,6.67,6.67,10.00,...,0.0,0.0,0.0,0.0,0.0,0.038,-0.544,0.530,0.080,-0.392

Data splitting

In [70]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x2, y, test_size = 0.2, random_state = 42, stratify = y)

Model Building

In [71]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [114]:
clf = RandomForestClassifier(n_estimators = 500, random_state = 42)
clf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=500, random_state=42)

In [115]:
y_pred = clf.predict(x_test)

In [116]:
print('Accuracy:', clf.score(x_test, y_test))

Accuracy: 0.7101449275362319

In [117]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      0.73      0.72       285
           1       0.70      0.69      0.70       267

    accuracy                           0.71       552
   macro avg       0.71      0.71      0.71       552
weighted avg       0.71      0.71      0.71       552

In [118]:
print(confusion_matrix(y_test, y_pred))

[[207  78]
 [ 82 185]]

In [109]:
!pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.3.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from lazypredict) (8.4.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (1.6.1)
Requirement already satisfied: pandas>=1.3 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (2.2.2)
Requirement already satisfied: tqdm>=4.0 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (4.67.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (1.5.3)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->lazypredict) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->lazypredict) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->lazypredict) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->lazypredict) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->lazypredict) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3->lazypredict) (1.17.0)
Downloading lazypredict-0.3.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 3.5 MB/s eta 0:00:00
Installing collected packages: lazypredict
Successfully installed lazypredict-0.3.0

In [110]:
import lazypredict
from lazypredict.Supervised import LazyClassifier
from sklearn.metrics import matthews_corrcoef

clz = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=matthews_corrcoef)
models, predictions = clz.fit(x_train, x_test, y_train, y_test)

In [112]:
print(models)

                               Accuracy  Balanced Accuracy   ROC AUC  \
Model
RidgeClassifier                0.740942           0.742854  0.787759
SVC                            0.740942           0.741672  0.774105
NuSVC                          0.739130           0.740035  0.753315
CalibratedClassifierCV         0.737319           0.739109  0.781924
LinearSVC                      0.735507           0.736882  0.782213
RidgeClassifierCV              0.733696           0.735364  0.786313
LinearDiscriminantAnalysis     0.731884           0.733964  0.788521
BernoulliNB                    0.731884           0.732663  0.766509
NearestCentroid                0.726449           0.727637  0.755878
LogisticRegression             0.717391           0.718273  0.782266
RandomForestClassifier         0.708333           0.708082  0.729811
QuadraticDiscriminantAnalysis  0.706522           0.703844  0.773763
ExtraTreesClassifier           0.699275           0.698600  0.649392
GaussianNB                     0.693841           0.695348  0.733392
AdaBoostClassifier             0.684783           0.684920  0.753361
LGBMClassifier                 0.684783           0.684802  0.778113
XGBClassifier                  0.681159           0.681057  0.771214
SGDClassifier                  0.675725           0.675439  0.742749
Perceptron                     0.670290           0.669584  0.730541
PassiveAggressiveClassifier    0.659420           0.658703  0.710014
BaggingClassifier              0.653986           0.652612  0.711427
KNeighborsClassifier           0.625000           0.633176  0.719068
DecisionTreeClassifier         0.606884           0.604869  0.622531
ExtraTreeClassifier            0.588768           0.586970  0.608437
DummyClassifier                0.516304           0.500000  0.500000
LabelPropagation               0.472826           0.459905       NaN
LabelSpreading                 0.472826           0.459905       NaN

                               F1 Score  Precision    Recall  \
Model
RidgeClassifier                0.740344   0.746461  0.740942
SVC                            0.740956   0.742378  0.740942
NuSVC                          0.739096   0.741006  0.739130
CalibratedClassifierCV         0.736805   0.742265  0.737319
LinearSVC                      0.735264   0.738822  0.735507
RidgeClassifierCV              0.733263   0.738108  0.733696
LinearDiscriminantAnalysis     0.731108   0.738100  0.731884
BernoulliNB                    0.731884   0.733442  0.731884
NearestCentroid                0.726292   0.729124  0.726449
LogisticRegression             0.717354   0.719203  0.717391
RandomForestClassifier         0.708350   0.708371  0.708333
QuadraticDiscriminantAnalysis  0.704262   0.709569  0.706522
ExtraTreesClassifier           0.699133   0.699156  0.699275
GaussianNB                     0.693435   0.697430  0.693841
AdaBoostClassifier             0.684865   0.685236  0.684783
LGBMClassifier                 0.684857   0.685093  0.684783
XGBClassifier                  0.681218   0.681348  0.681159
SGDClassifier                  0.675743   0.675765  0.675725
Perceptron                     0.670134   0.670136  0.670290
PassiveAggressiveClassifier    0.659259   0.659254  0.659420
BaggingClassifier              0.653307   0.653874  0.653986
KNeighborsClassifier           0.601070   0.679048  0.625000
DecisionTreeClassifier         0.605306   0.606649  0.606884
ExtraTreeClassifier            0.587488   0.588260  0.588768
DummyClassifier                0.351605   0.266570  0.516304
LabelPropagation               0.374038   0.396790  0.472826
LabelSpreading                 0.374038   0.396790  0.472826

                               matthews_corrcoef  Time Taken
Model
RidgeClassifier                         0.487968    0.198912
SVC                                     0.483289    1.695740
NuSVC                                   0.480197    1.782468
CalibratedClassifierCV                  0.480099    3.803010
LinearSVC                               0.474637    0.640311
RidgeClassifierCV                       0.472266    0.308439
LinearDiscriminantAnalysis              0.470658    0.355078
BernoulliNB                             0.465326    0.113170
NearestCentroid                         0.455797    0.110634
LogisticRegression                      0.436661    0.487219
RandomForestClassifier                  0.416118    1.281715
QuadraticDiscriminantAnalysis           0.414048    0.396233
ExtraTreesClassifier                    0.397577    1.901872
GaussianNB                              0.391735    0.143900
AdaBoostClassifier                      0.369646    0.827011
LGBMClassifier                          0.369429    0.807482
XGBClassifier                           0.361980    2.382631
SGDClassifier                           0.350838    0.341170
Perceptron                              0.339490    0.086846
PassiveAggressiveClassifier             0.317707    0.142794
BaggingClassifier                       0.306424    1.372418
KNeighborsClassifier                    0.305929    0.236858
DecisionTreeClassifier                  0.211433    0.255134
ExtraTreeClassifier                     0.175028    0.079005
DummyClassifier                         0.000000    0.064260
LabelPropagation                       -0.130682    0.866406
LabelSpreading                         -0.130682    0.808692